// <auto-generated />
namespace ProyectoFinal_RentCar.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Renta_DevolucionAgregoDevolucion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Renta_DevolucionAgregoDevolucion));
        
        string IMigrationMetadata.Id
        {
            get { return "202205262144069_Renta_Devolucion-Agrego-Devolucion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
